# Generated by Django 4.1.4 on 2023-01-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gundam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('shippingCost', models.IntegerField()),
                ('shippingDate', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=2000)),
            ],
        ),
    ]
